version: '3.9'
services:
  backend:
    build:
      context: ./shopper-backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    volumes:
      - .env:/app/.env

  frontend:
    build:
      context: ./shopper-app-react
    ports:
      - "80:3000"
